name: CI and CD

on:
  push:
    branches:
      - actions/tests-develop
jobs:
    build-and-test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Merge a rama de develop
          run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "actions"
            git fetch origin ${{ github.event.pull_request.head.ref }}
            git fetch --all
            git switch actions/tests-develop
            git pull origin actions/tests-develop
            git switch ${{ github.event.pull_request.head.ref }}
            git rebase actions/tests-develop

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'
            cache: 'gradle'

        - name: run tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 29
            script: ./gradlew connectedCheck