name: CI and CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.3
          components: platform-tools, emulator, "system-images;android-33;google_apis;x86_64"

      - name: Accept Licenses
        run: |
          yes | sdkmanager --licenses

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Run Unit Tests
        run: ./gradlew test

  create-release-branch-and-build-apk:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print last commit message
        id: commit_message
        run: |
          echo "Last commit message: ${{ github.event.head_commit.message }}"
          echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Check for Release version in commit message
        id: check_version
        run: |
          if [[ "${{ env.commit_message }}" =~ ^Release\ [0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "Valid release message found."
            echo "release_found=true" >> $GITHUB_ENV
          else
            echo "No valid release message found."
            echo "release_found=false" >> $GITHUB_ENV
          fi

      - name: Extract version number
        id: extract_version
        if: env.release_found == 'true'
        run: |
          version=$(echo "${{ env.commit_message }}" | grep -oP 'Release \K[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=$version" >> $GITHUB_ENV

      - name: Debug git configuration
        run: |
          git config --list
          git remote -v

      - name: Push release branch to origin
        if: env.release_found == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Usar el token personal de acceso
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/jchernandezUA/vinylOS-ua.git"
          git checkout develop
          git checkout -b release/$version
          git push origin release/$version

      - name: Set up JDK 17
        if: env.release_found == 'true'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle packages
        if: env.release_found == 'true'
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Decode Keystore
        if: env.release_found == 'true'
        run: |
          echo "${{ secrets.KEY_STORE }}" | base64 -d > app/my-release-key.jks

      - name: Build APK
        if: env.release_found == 'true'
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Check APK Existence
        if: env.release_found == 'true'
        run: |
          ls -l app/build/outputs/apk/release/

      - name: Release
        if: env.release_found == 'true'
        uses: ncipollo/release-action@v1.10.0
        with:
          tag: v$version
          name: Release $version
          draft: false
          prerelease: false
          artifacts: app/build/outputs/apk/release/app-release.apk
          generateReleaseNotes: false
          omitBody: false
          omitBodyDuringUpdate: false
          omitDraftDuringUpdate: false
          omitName: false
          omitNameDuringUpdate: false
          omitPrereleaseDuringUpdate: false
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Merge release branch into main
        if: env.release_found == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Usar el token personal de acceso
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/jchernandezUA/vinylOS-ua.git"
          git fetch --all 
          git checkout main
          git merge --ff-only --allow-unrelated-histories release/$version
          git push origin main
